development:
  adapter: postgresql
  encoding: unicode
  database: appdeployment_development
  pool: 5
  host: localhost
  username: dbuser
  password: dbuser

test:
  adapter: postgresql
  encoding: unicode
  database: appdeployment_test
  pool: 5
  host: localhost
  username: dbuser
  password: dbuser
  
production:
  adapter: postgresql
  encoding: unicode
  database: appdeployment_production
  pool: 5
  host: localhost
  username: dbuser
  password: ENV["DB_PASSWORD"]
  

